version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      tarrget: prod
    container_name: app-production
    image: app
    ports:
      - 3000:3000
    init: true
