version: '3'

services:
  app:
    build: .
    volumes:
      - ..:/workspace:cached
      - /workspace/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db
    tty: true

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_development
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user

volumes:
  dbdata:
